accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('posts/',include('posts.urls')),
    path('accounts/', include('allauth.urls')), #accounts가 두개가 있어도 상관없다.
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='list'), 
    path('create/',views.PostCreate.as_view(),name='create'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings # 추천!


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1) # 추천!

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView,CreateView,DetailView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class PostList(ListView):
    model = Post
    
class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title','content')
    success_url = reverse_lazy('posts:list')

accounts/templates/accounts/login.html
{%extends 'base.html'%}
{% load socialaccount %}


{%block content%}
    <form method='post'>
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
    {% providers_media_js %}
    <a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect 
    <i class="fab fa-facebook-square"></i>
    </a>
{%endblock%}

posts/templates/posts/post_base.html
{%extends 'base.html'%}
{%block content%}
    <a href="{%url 'posts:create'%}">글작성</a>
    {%block body%}
    {%endblock%}
{%endblock%}

posts/templates/posts/post_form.html
{%extends 'posts/post_base.html'%}
{%block body%}

<form method='post'>
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit"/>
</form>
{%endblock%}

posts/templates/posts/post_list.html
{%extends 'posts/post_base.html'%}
{%block body%}
    {%for post in post_list%}
        <h1>{{post.title}}</h1>
    {%endfor%}
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{%url 'accounts:logout'%}">로그아웃</a>
    {% else %}
        <a href="{%url 'accounts:login'%}">로그인</a>
    {% endif %}
    {%block content%}
    <a>
    <i class="fab fa-facebook-square"></i>
    facebook connect
    </a>
    {%endblock%}
</body>

</html>